apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "vote-ui-labels" . }}
  name: {{ .Values.product.name }}-{{ .Values.apps.vote_ui.name }}-service
spec:
  type: {{ .Values.apps.vote_ui.service.type }}
  ports:
    - name: {{ .Values.apps.vote_ui.name }}
      port: {{ .Values.apps.vote_ui.service.port }}
      targetPort: 80
      {{- if eq .Values.apps.vote_ui.service.type "NodePort" }}
      nodePort: {{ .Values.apps.vote_ui.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.apps.vote_ui.name }}
