apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "redis-labels" . }}
  name: {{ .Values.product.name }}-{{ .Values.apps.redis.name }}-service
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.apps.redis.name }}
      port: 6379
      targetPort: 6379
  selector:
    {{ include "redis-labels" . }}
