services:
  vote:
    image: dockersamples/examplevotingapp_vote
    # ports:
    #   - 5500:80
    networks:
      - backend
      - proxy
    labels:
      - "loki_enable=true"
      - "service_group=application"
      - "product_name=docker-samples"
      - "app_name=vote"
      - "app_environment=production"
      - "caddy=vote.local"
      - "caddy.reverse_proxy={{upstreams 80}}"

volumes:
  db-data:

networks:
  backend:
    external: true
  proxy:
    external: true
