services:
  vote:
    image: dockersamples/examplevotingapp_vote
    # ports:
    #   - 5500:80
    networks:
      - backend
      - proxy
    deploy:
      replicas: 1
      labels:
        - "caddy=vote.local"
        - "caddy.reverse_proxy={{upstreams 80}}"
    labels:
      - "loki_enable=true"
      - "service_group=application"
      - "product_name=docker-samples"
      - "app_name=vote"
      - "app_environment=production"

volumes:
  db-data:

networks:
  backend:
    external: true
  proxy:
    external: true
