network:
  version: 2
  ethernets:
    ens18:
      dhcp4: no
      addresses:
        - 10.10.10.101/24
      routes:
        - to: default
          via: 10.10.10.1
      nameservers:
        addresses:
          - 1.1.1.1
        search:
          - homelab.local
