apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ include "labels" . }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "labels" . }}
  template:
    metadata:
      labels:
        {{ include "labels" . }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          name: {{ .Values.app.name }}
