app:
  name: result

replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: dockersamples/examplevotingapp_result
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

service:
  type: NodePort
  port: 8081
  nodePort: 31001
  name: 'result-service'
