services:
  alertmanager:
    image: prom/alertmanager:v0.28.0
    volumes:
      - ./docker/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    ports:
      - '9093:9093'
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    labels:
      - 'service_group=monitoring'
      - 'node_name=monitor'
      - 'app_name=alertmanager'

  caddy:
    image: caddy:2.8
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_monitoring_data:/data
      - caddy_monitoring_config:/config
    ports:
      - '443:443' # Only expose HTTPS for Grafana
      - '80:80' # For HTTP redirect
    env_file:
      - ./docker/caddy/.env
    labels:
      - 'service_group=monitoring'
      - 'node_name=monitor'
      - 'app_name=caddy'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'
    deploy:
      mode: global
    labels:
      - 'service_group=monitoring'
      - 'node_name=monitor'
      - 'app_name=cadvisor'

  grafana:
    image: grafana/grafana:11.5.2
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3000:3000'
    env_file:
      - ./docker/grafana/.env
    labels:
      - 'service_group=monitoring'
      - 'node_name=monitor'
      - 'app_name=grafana'
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:3.4.2
    volumes:
      - loki_data:/loki
      - ./docker/loki:/mnt/config
    command:
      - '-config.file=/mnt/config/loki-config.yml'
      - '-config.expand-env=true'
    ports:
      - '3100:3100'
      - '9096:9096'
    labels:
      - 'service_group=monitoring'
      - 'node_name=monitor'
      - 'app_name=loki'

  node_exporter:
    image: prom/node-exporter:v1.9.0
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    ports:
      - '9100:9100'
    deploy:
      mode: global
    labels:
      - 'service_group=monitoring'
      - 'node_name=monitor'
      - 'app_name=node-exporter'

  prometheus:
    image: prom/prometheus:v3.2.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - alertmanager
    labels:
      - 'service_group=monitoring'
      - 'node_name=monitor'
      - 'app_name=prometheus'

volumes:
  alertmanager_data:
  caddy_monitoring_config:
  caddy_monitoring_data:
  grafana_data:
  loki_data:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
