configs:
  alloy_config:
    file: ./config.alloy

services:
  alloy:
    image: grafana/alloy:v1.7.1
    hostname: "{{ .Node.Hostname }}"
    configs:
      - source: alloy_config
        target: /etc/alloy/config.alloy
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    deploy:
      mode: global
    env_file:
      - ./docker/alloy/.env
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'product_name=docker-samples'
      - 'app_name=alloy'
      - 'app_environment=production'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'product_name=docker-samples'
      - 'app_name=cadvisor'
      - 'app_environment=production'

  node_exporter:
    image: prom/node-exporter:v1.9.0
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    deploy:
      mode: global
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'product_name=docker-samples'
      - 'app_name=node-exporter'
      - 'app_environment=production'

  redis:
    image: redis:alpine
    deploy:
      placement:
        constraints:
          - node.labels.private != true
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=docker-samples'
      - 'app_name=redis'
      - 'app_environment=production'

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.private != true
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=docker-samples'
      - 'app_name=db'
      - 'app_environment=production'

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5500:80
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.private != true
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=docker-samples'
      - 'app_name=vote'
      - 'app_environment=production'

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 5000:80
    deploy:
      placement:
        constraints:
          - node.labels.private != true
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=docker-samples'
      - 'app_name=result'
      - 'app_environment=production'

  result-customer-1:
    image: dockersamples/examplevotingapp_result
    deploy:
      placement:
        constraints:
          - node.labels.customer == one
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=docker-samples'
      - 'app_name=result-customer-1'
      - 'app_environment=production'

  worker:
    image: dockersamples/examplevotingapp_worker
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.private != true
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=docker-samples'
      - 'app_name=worker'
      - 'app_environment=production'

volumes:
  db-data:
