apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "labels" . }}
  name: {{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.app.name }}-service
      port: 6379
      targetPort: 6379
  selector:
    {{ include "labels" . }}
