services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'app_name=cadvisor'
      - 'app_environment=monitoring'
      - 'product_name=monitoring-stack'

  grafana:
    image: grafana/grafana:11.5.2
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3000:3000'
    env_file:
      - ./docker/grafana/.env
    labels:
      - 'loki_enable=true'
      - 'service_group=monitoring'
      - 'app_name=grafana'
      - 'app_environment=monitoring'
      - 'product_name=monitoring-stack'
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:3.4.2
    volumes:
      - loki_data:/loki
      - ./docker/loki:/mnt/config
    command:
      - '-config.file=/mnt/config/loki-config.yml'
      - '-config.expand-env=true'
    ports:
      - '3100:3100'
      - '9096:9096'
    labels:
      - 'loki_enable=true'
      - 'service_group=monitoring'
      - 'app_name=loki'
      - 'app_environment=monitoring'
      - 'product_name=monitoring-stack'

  node_exporter:
    image: prom/node-exporter:v1.9.0
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    deploy:
      mode: global
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'app_name=node-exporter'
      - 'app_environment=monitoring'
      - 'product_name=monitoring-stack'

  prometheus:
    image: prom/prometheus:v3.2.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    labels:
      - 'loki_enable=true'
      - 'service_group=monitoring'
      - 'app_name=prometheus'
      - 'app_environment=monitoring'
      - 'product_name=monitoring-stack'

volumes:
  caddy_monitoring_config:
  caddy_monitoring_data:
  grafana_data:
  loki_data:
  prometheus_data:
