global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]
      api_version: v2

scrape_configs:
  # 1. Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 2. Monitor local node-exporter
  - job_name: "node"
    metrics_path: /metrics
    relabel_configs:
      - target_label: hostname
        replacement: monitor
    static_configs:
      - targets: ["node_exporter:9100"]

  # 3. Monitor local cAdvisor
  - job_name: "cadvisor"
    metrics_path: /metrics
    relabel_configs:
      - target_label: hostname
        replacement: monitor
    static_configs:
      - targets: ["cadvisor:8080"]
