version: '3.9'

services:
  alloy:
    image: grafana/alloy:v1.7.1
    volumes:
      - ./docker/alloy:/etc/alloy
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    deploy:
      mode: global
    env_file:
      - ./docker/alloy/.env
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'product_name=voting-app'
      - 'app_name=alloy'
      - 'app_environment=production'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    deploy:
      replicas: 1
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'product_name=voting-app'
      - 'app_name=cadvisor'
      - 'app_environment=production'

  node_exporter:
    image: prom/node-exporter:v1.9.0
    deploy:
      mode: global
    labels:
      - 'loki_enable=false'
      - 'service_group=monitoring'
      - 'product_name=voting-app'
      - 'app_name=node-exporter'
      - 'app_environment=production'

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    labels:
      - 'loki_enable=false'
      - 'service_group=storage'
      - 'product_name=voting-app'
      - 'app_name=db'
      - 'app_environment=production'

  redis:
    image: redis:alpine
    networks:
      - frontend
      - backend
    labels:
      - 'loki_enable=false'
      - 'service_group=storage'
      - 'product_name=voting-app'
      - 'app_name=redis'
      - 'app_environment=production'

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - 8082:80
    networks:
      - backend
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=voting-app'
      - 'app_name=result'
      - 'app_environment=production'

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 8081:80
    networks:
      - frontend
    deploy:
      replicas: 2
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=voting-app'
      - 'app_name=vote'
      - 'app_environment=production'

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2
    labels:
      - 'loki_enable=true'
      - 'service_group=application'
      - 'product_name=voting-app'
      - 'app_name=worker'
      - 'app_environment=production'

networks:
  frontend:
  backend:

volumes:
  db-data:
