apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "labels" . }}
  name: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.app.name }}
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.app.name }}
