- targets:
    - '192.168.56.6:8080'  # app-server cadvisor
  labels:
    product: voting-app
    environment: production
    node: app-server

- targets:
    - '192.168.56.7:8080'  # monitor cadvisor
  labels:
    product: monitoring
    environment: production
    node: monitor
