- targets:
    - '192.168.56.6:9100'  # app-server node-exporter
  labels:
    product: voting-app
    environment: production
    node: app-server

- targets:
    - '192.168.56.7:9100'  # monitor node-exporter
  labels:
    product: monitoring
    environment: production
    node: monitor
